---
title: "Victoria Mello's Website"
output: 
  html_document:
    toc: true
    toc_float: true
---
<style>
  body {
    font-size: 16px; /
  }
</style>

### About
Hello! I’m Victoria Mello, a recent graduate from Columbia University’s Mailman School of Public Health, where I completed my Master of Public Health in Sociomedical Sciences with a Research Methods certificate in May 2024. My professional interests revolve around leveraging mixed-methods approaches to thoroughly analyze and address complex public health issues. I am passionate about advancing research that works directly with those most affected by deep-seated health disparities and developing evidence-based programs and policies that prioritize crucial social determinants of health as essential pathways to achieving true health equity.

This website includes information about me, such as my [resume](resume.html) where you can read both my [undergraduate](VMthesis.pdf) and [master's](Mello_Thesis_MPH.pdf) theses. Additionally, you can find examples of spatial analyses I have created using [QGIS](QGIS.html). This website, along with my [final project](https://nn2477.github.io/p8105-fp-rats.github.io/index.html) NYC rat analysis website, were created using RStudio and GitHub for assignments in a 'Data Science' course I took during my masters program. Some examples of basic interactive data visualizations I created with plotly can be found on my [dashboard](dashboard.html) as well. For a writing sample, please check out [this paper](WritingSample.html) I submitted as my final exam for my Health Promotion Theory course. Now sit back, relax, and please enjoy exploring my website!
