---
title: "Victoria Mello's Website"
output: 
  html_document:
    toc: true
    toc_float: true
---
<style>
  body {
    font-size: 16px; /
  }
</style>

### About
Hello! My name is Victoria Mello, and I am a Master of Public Health student in the Sociomedical Sciences department at Columbia University Mailman School of Public Health, specializing in research methods. My academic journey centers on the application of mixed-methods to comprehensively analyze and address complex public health challenges. Driven by a profound passion for promoting equity, I am particularly interested in advocating for programs and policies that contribute to social, economic, environmental, and health equity. This website includes information such as my [resume](resume.html) as well as some examples of spatial analyses I have created in [QGIS](QGIS.html). This website along with my [final project](https://nn2477.github.io/p8105-fp-rats.github.io/index.html) NYC rat analysis website were created using RStudio. Examples of some interactive data visualizations I made using plotly can be found on my [dashboard](dashboard.html) as well. Below you will find a graduation photo of me from my time in undergrad at Brown University, where I earned my B.A. in Public Health with honors distinction. Please feel free to read my [undergrad thesis](VMthesis.pdf) that I wrote to graduate with honors in my program. I hope you enjoy exploring my personal website! 


 


 