---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---
<style>
  body {
    font-size: 15px; /
  }
</style>

### Victoria Mello
- Phone: (508) 981-9810
- E-Mail: victoria_mello@alumni.brown.edu
- E-Mail: vsm2118@cumc.columbia.edu

### Education

##### Columbia University, Mailman School of Public Health
* New York, NY
* Master of Public Health, Department of Sociomedical Sciences
* Certificate in Research Methods
* GPA: 4.0
* September 2022 - May 2024
* [Read My Masters Thesis](Mello_Thesis_MPH.pdf)

##### Brown University
* Providence, RI
* Honors B.A. Public Health
* GPA: 3.9
* September 2018 - May 2022
* [Read My Honors Thesis](VMthesis.pdf)

### Experience

##### Columbia Mailman, Graduate Research Assistant  |  New York, NY | January 2024 – May 2024
* Utilized SPSS for analysis of primary survey data from a novel undergraduate naloxone training program, integrating Theory of Planned Behavior (TPB) to inform analysis and prepare results for write-up and publication.
* Contributed to Dr. Shelton's dissemination and implementation science projects through weekly team meetings, scoring survey items, data analysis and literature reviews, as well as applying health behavior theory.
* Conducted a three-way vertical merge of participant data from baseline, post-test, and follow-up surveys, ensuring clean integration into a unified SPSS .sav file.

##### Abt Associates, Social Impact Research and Consulting Internship  |  New York, NY | June 2023 – August 2023
* Worked collaboratively with multidisciplinary teams on two large-scale program evaluations contracted by the US government, participating in tasks related to data analysis, research, and drafting various report sections.
* Supported the research and data extraction efforts for a large-scale evaluation of Diabetes Prevention Programs, contributing to the compilation of implementer and participant-level implementation outcome measures as well as psychometric validity measures across thousands of domestic programs to inform evidence-based recommendations.
* Worked within a supporting documentation team for a large evaluation project contracted by a federal agency, contributing to the research and report drafting process focused on analyzing the impact of specific diagnostic disability codes on individuals' earning potential and quality of life.
* Participated in professional development sessions to enhance research, data analysis, and overall writing skills.

##### Brown University, Public Health Honors Thesis  |  Providence, RI | September 2021 – May 2022
* Conducted qualitative research and literature review of programmatic adaptations to medications for opioid use disorder (MOUD) in light of COVID-19 and policy changes easing strict regulations for MOUD delivery.
* Conducted data analysis with SAS on the 2019 and 2020 SAMHSA National Survey of Substance Abuse Treatment Services (N-SSATS) datasets to compare MOUD availability across all US facilities pre versus post policy changes. 
* Met bi-weekly with thesis advisor, Dr. Moyo, for guidance and to discuss next steps. Dedicated an average of 7-10 hours weekly to research and synthesize the thesis for the final review and faculty presentation in the spring.

##### Lifespan Health Network, Connect for Health, Patient Liaison  |  Providence, RI | January 2020 – May 2022

* Volunteered through Connect for Health at Brown University to address social determinants of health for low-income patients at the Center for Primary Care (CPC) in Providence by connecting patients with local and government resources to assist with basic needs such as housing stability, clothing, and food access.
* Managed relationships with 3-4 clients at a time and dedicated 8-10 hours weekly to provide support resources and assist patients with applications to SNAP, rent and utility assistance programs, homeless shelters, etc. 
* Used the Lifespan Network “REACH” software to research helpful resources for clients while following HIPAA guidelines for all clients at the CPC desk and in clinical communications with physicians. 

##### edHEALTH, Research Internship  |  Barrington, RI | June 2020 – August 2020
* Spearheaded the initial drafting of PBM Request for Proposal (RFP) process for edHEALTH, an insurance consortium serving educational institutions, with the objective to reduce pharmaceutical costs for members. 
* Conducted research focused on understanding member’s needs which resulted in the discovery of a cost-effective “transparent” Pharmacy Benefit Manager (PBM), which requires proactive management of the drug formulary but also created room for significant pharmaceutical cost reduction via tailoring the formulary.
* Researched prospective pharmaceutical advisors who actively manage the drug formulary to reduce waste and significantly cut member’s costs. This research resulted in the discovery of a suitable consultant for member’s needs and catalyzed the undertaking of the RFP process for consulting services in 2021.

##### UMass Medical School, Mello Laboratory, Junior Lab Assistant  |  Worcester, MA | June 2019 – August 2019
* Studied the application of CRISPR-Cas9 while learning to utilize CRISPR technology on C. elegans in lab to assist lab members with conducting RNA therapeutics research projects.
* Prepared cell plates, sterilized equipment, and disposed of any contaminated or expired materials in the lab.


### Leadership

##### Graduate Teaching Assistant, Columbia Mailman School of Public Health |  New York, NY | September 2023 – December 2023
* Facilitated weekly discussions for two groups of 20 students, enhancing comprehension of course content in History, Human Rights, and Ethics within the 'Foundations of Public Health' course.
* Evaluated and graded student assignments, including papers and presentations, ensuring adherence to course objectives and providing constructive feedback.
* Conducted regular office hours to offer mentorship, clarify concepts, and support students in navigating course materials effectively.

##### Hospital Relations, Children’s Miracle Network Hospitals  |  Providence, RI | January 2019 – May 2022
* Worked with a small executive board to bring the 501(c)(3) nonprofit Dance Marathon Program to Brown University in 2019 as an annual fundraising organization for the local Hasbro Children’s Hospital. 
* Led the organization of all fundraising initiatives and facilitated communications with hospital representatives and our partnered "Miracle Families".


### Relevant Courses 
* Data Science (learning RStudio)
* Public Health GIS (learning QGIS)
* Methods in Program Evaluation 
* Managing Public Health Non-Profits (grant writing)
* Qualitative Research Methods (learning NVivo)
* Quantitative Research Methods (learning SPSS)
* Community Based Participatory Research (CBPR)
* Designing Public Health Interventions (program implementation)
* Health Promotion Theory

