---
title: "Writing Sample"
output: 
  html_document:
    toc: true
    toc_float: true
---
<style>
  body {
    font-size: 16px; /
  }
</style>

### Prompt
I wrote this final paper for my Health Promotion and Theory course that I took during my MPH program. The prompt asked us to design a communication intervention based in health promotion theory that will garner community support in East Harlem and convince residents that the Overdose Prevention Center (OPC) in their neighborhood is a safe and effective way to reduce opioid overdoses, save lives, and benefits all members of the community. We were required to outline the impact of the opioid epidemic in NYC as well as design a multi-level campaign that targeted at least two levels of the social ecological model by utilizing constructs from various health behavior theories. I genuinely enjoyed learning more about the East Harlem community and brainstorming strategies based on health promotion theory to increase local support for the OPC while researching and writing this piece. I hope you enjoy reading it as much as I enjoyed writing it!

[Read my Health Promotion Paper Here!](Health_Behavior_Theory.pdf)
